spring.application.name=worklog

# Database Configuration - Prod (Using Environment Variables)
# The syntax ${VAR_NAME:default_value} means: "Use the environment variable VAR_NAME. If it doesn't exist, use the default value."
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/worklog}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration - Prod
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# DevTools Configuration - ENABLE AUTO-RESTART
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

jwt.secret=${JWT_SECRET:mysuperlongsecretkeywithatleast32chars!}
